"""Label-first synthetic generation for cotton fiber crossings.

The generation direction is inverted with respect to a conventional annotation pipeline:
the geometry (and therefore the label) is sampled FIRST, and the observation is rendered
FROM that geometry.  Every image/label pair is exact by construction and costs nothing
to annotate.

Three properties distinguish this generator from a generic curve simulator:

* **Equal-staple prior.**  Every fiber is a worm-like chain integrated to exactly
  `staple_pixels` of arc length, because the specimen fibers are all cut to the same
  35 mm staple.  Length is a hard constraint of the sampler, not a random draw.

* **Guaranteed complete crossings.**  At least one crossing per canvas is *verified*
  complete: its intersection point is interior by `margin`, and all four arms remain
  inside the canvas for at least `arm_pixels` of arc length.  Canvases that fail the
  check are resampled, so the network never has to learn a crossing from a clipped one.

* **Background-carrier rendering.**  The substrate comes from real *training-split*
  tiles whose thin bright structures have been removed morphologically, so grain,
  speckle and illumination statistics are real while the fiber content is synthetic.

Emitted labels (all exact, all free):
  mask, center, joint heatmap, 4 orientation moments, overlap multiplicity,
  per-instance centerlines, crossing coordinates + completeness flags, instance id map.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import cv2
import numpy as np
from scipy.ndimage import gaussian_filter

from .common import load_json, read_image, save_json, write_image

# A case name is a SAMPLING STRATEGY, not a label.  Every exported label is computed
# from the curves that were actually drawn, so a canvas generated by the "near_miss"
# strategy whose fibers happen to touch is still labelled as crossing there.
CASES = ["random", "cross", "acute", "orthogonal", "parallel", "near_miss", "multi", "empty"]
CASE_P = [0.26, 0.18, 0.14, 0.10, 0.07, 0.08, 0.12, 0.05]


# --------------------------------------------------------------------------- geometry
def worm_chain(rng, start_xy, theta0, arc_length, persistence, step=2.0, kink_rate=0.0015):
    """Worm-like chain with fixed arc length.

    The tangent angle performs a correlated random walk with standard deviation set by
    the persistence length, so the curve is smooth at the fiber scale while still
    wandering over the plate.  Rare kinks emulate the sharp bends cotton fibers take
    where they have been folded.
    """
    n = max(8, int(round(arc_length / step)))
    sigma = np.sqrt(step / max(persistence, 1e-3))
    dtheta = rng.normal(0.0, sigma, n)
    kinks = rng.random(n) < kink_rate * step
    dtheta[kinks] += rng.normal(0.0, 0.7, int(kinks.sum())) * rng.choice([-1.0, 1.0], int(kinks.sum()))
    theta = theta0 + np.cumsum(dtheta)
    dx = np.cos(theta) * step
    dy = np.sin(theta) * step
    pts = np.stack([np.concatenate([[0.0], np.cumsum(dx)]),
                    np.concatenate([[0.0], np.cumsum(dy)])], axis=1)
    return (pts + np.asarray(start_xy, dtype=float)).astype(np.float32)


def chain_through(rng, point_xy, theta, arc_length, persistence, before=0.5, step=2.0):
    """A fixed-length chain that passes through `point_xy` with tangent `theta`.

    `before` is the fraction of the staple length that lies on the incoming side, so the
    crossing can sit anywhere along the fiber, not only at its midpoint.
    """
    back = worm_chain(rng, point_xy, theta + np.pi, arc_length * before, persistence, step)
    fwd = worm_chain(rng, point_xy, theta, arc_length * (1.0 - before), persistence, step)
    return np.concatenate([back[::-1][:-1], fwd], axis=0).astype(np.float32)


def segment_intersections(a, b):
    """All proper intersections between two polylines, with arc-length positions."""
    p = a[:-1, None, :]
    r = np.diff(a, axis=0)[:, None, :]
    q = b[None, :-1, :]
    s = np.diff(b, axis=0)[None, :, :]

    def cross(u, v):
        return u[..., 0] * v[..., 1] - u[..., 1] * v[..., 0]

    den = cross(r, s)
    valid = np.abs(den) > 1e-9
    safe = np.where(valid, den, 1.0)
    t = cross(q - p, s) / safe
    u = cross(q - p, r) / safe
    good = valid & (t >= 0) & (t < 1) & (u >= 0) & (u < 1)
    idx = np.argwhere(good)
    out = []
    for i, j in idx:
        pt = a[i] + t[i, j] * (a[i + 1] - a[i])
        out.append((pt, int(i), int(j)))
    return out


def _arc_inside(curve, index, size, margin=0):
    """Arc length the curve keeps inside the canvas on each side of vertex `index`."""
    inside = ((curve[:, 0] >= margin) & (curve[:, 0] < size - margin)
              & (curve[:, 1] >= margin) & (curve[:, 1] < size - margin))
    seg = np.linalg.norm(np.diff(curve, axis=0), axis=1)
    back = 0.0
    for k in range(index, 0, -1):
        if not (inside[k] and inside[k - 1]):
            break
        back += seg[k - 1]
    fwd = 0.0
    for k in range(index, len(seg)):
        if not (inside[k] and inside[k + 1]):
            break
        fwd += seg[k]
    return back, fwd


def crossing_records(curves, size, arm_pixels, margin):
    """Every pairwise crossing, tagged with whether it is complete inside the canvas."""
    records = []
    for i in range(len(curves)):
        for j in range(i + 1, len(curves)):
            for pt, ia, ib in segment_intersections(curves[i], curves[j]):
                x, y = float(pt[0]), float(pt[1])
                if not (0 <= x < size and 0 <= y < size):
                    continue
                if any(abs(x - r["xy"][0]) < 4 and abs(y - r["xy"][1]) < 4 for r in records):
                    continue
                ba, fa = _arc_inside(curves[i], ia, size)
                bb, fb = _arc_inside(curves[j], ib, size)
                interior = margin <= x < size - margin and margin <= y < size - margin
                complete = bool(interior and min(ba, fa, bb, fb) >= arm_pixels)
                records.append(dict(xy=[x, y], fibers=[i, j], complete=complete,
                                    arms=[float(ba), float(fa), float(bb), float(fb)]))
    return records


def make_geometry(rng, size, case, staple, arm_pixels, margin, max_tries=40,
                  equal_length=True, require_complete=True):
    """Sample curves for one canvas, enforcing at least one complete crossing.

    `equal_length=False` and `require_complete=False` exist only to build the data
    ablations: they switch off the equal-staple prior and the completeness guarantee
    respectively, so their contribution can be measured rather than asserted.
    """
    if case == "empty":
        return [], []
    # A near miss only reads as a near miss if the fibers stay straight enough not to
    # wander back into each other, so that strategy draws a long persistence length.
    persistence = float(rng.uniform(900.0, 2500.0) if case == "near_miss"
                        else rng.uniform(60.0, 400.0))
    tries = max_tries if require_complete else 1
    for _ in range(tries):
        length_a = staple if equal_length else staple * float(rng.uniform(0.35, 1.6))
        length_b = staple if equal_length else staple * float(rng.uniform(0.35, 1.6))
        centre = rng.uniform(margin + 8, size - margin - 8, 2)
        theta_a = rng.uniform(0, np.pi)
        if case == "cross":
            delta = rng.uniform(0.60, 1.20)
        elif case == "acute":
            delta = rng.uniform(0.14, 0.45)
        elif case == "orthogonal":
            delta = rng.uniform(1.40, 1.74)
        elif case == "parallel":
            delta = rng.uniform(0.02, 0.10)
        elif case == "near_miss":
            delta = rng.uniform(0.5, 1.3)
        else:
            delta = rng.uniform(0.25, 1.50)
        theta_b = theta_a + delta * rng.choice([-1.0, 1.0])
        curves = [
            chain_through(rng, centre, theta_a, length_a, persistence,
                          float(rng.uniform(0.25, 0.75))),
            chain_through(rng, centre, theta_b, length_b, persistence,
                          float(rng.uniform(0.25, 0.75))),
        ]
        if case == "near_miss":
            # Displace the second fiber sideways so the pair approaches but never meets.
            offset = np.array([-np.sin(theta_b), np.cos(theta_b)]) * rng.uniform(6.0, 14.0)
            curves[1] = curves[1] + offset
        extra = {"multi": int(rng.integers(2, 5)), "random": int(rng.integers(0, 3))}.get(case, 0)
        for _ in range(extra):
            start = rng.uniform(-0.2, 1.2, 2) * size
            length = staple if equal_length else staple * float(rng.uniform(0.35, 1.6))
            curves.append(worm_chain(rng, start, rng.uniform(0, 2 * np.pi), length, persistence))
        records = crossing_records(curves, size, arm_pixels, margin)
        if not require_complete:
            return curves, records
        if case == "near_miss":
            if not any(r["complete"] for r in records):
                return curves, records
            continue
        if any(r["complete"] for r in records):
            return curves, records
    return curves, records


# --------------------------------------------------------------------------- rendering
def suppress_fibers(tile):
    """Remove thin bright structures from a real tile, keep grain and illumination."""
    k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (9, 9))
    opened = cv2.morphologyEx(tile, cv2.MORPH_OPEN, k)
    # Residual wide halos are blended away, grain is preserved by the opening itself.
    return cv2.medianBlur(opened, 3)


def render(rng, curves, size, carrier=None, width_range=(2.0, 4.6), distractors=(),
           fades=0):
    """Render fibers over a background; returns the image and the exact label parts.

    `distractors` are short fiber-like curves drawn with the fiber appearance model but
    kept OUT of every label: lint and broken ends that are not staple fibers.  `fades`
    attenuates that many short stretches of the true fibers in the image while leaving
    their labels intact, the way a poorly focused or low-contrast stretch looks on a
    real plate.  Both default to off, which reproduces the original corpus exactly.
    """
    yy, xx = np.mgrid[:size, :size].astype(np.float32)
    if carrier is None:
        seed = rng.normal(0, 1, (10, 10)).astype(np.float32)
        base = cv2.resize(seed, (size, size), interpolation=cv2.INTER_CUBIC)
        bg = base * rng.uniform(0.01, 0.05) + rng.uniform(0.20, 0.62)
        bg = bg + gaussian_filter(rng.normal(0, rng.uniform(0.004, 0.030), (size, size)), 0.8)
    else:
        bg = carrier.astype(np.float32) / 255.0
    # Residual illumination tilt and vignette, matched to the plate optics.
    bg = bg + rng.uniform(-0.06, 0.06) * xx / size + rng.uniform(-0.06, 0.06) * yy / size
    radial = ((xx - size / 2) ** 2 + (yy - size / 2) ** 2) / (size * size)
    bg = bg - rng.uniform(0.0, 0.12) * radial

    mask = np.zeros((size, size), np.uint8)
    center = np.zeros((size, size), np.uint8)
    overlap = np.zeros((size, size), np.uint16)
    moments = np.zeros((4, size, size), np.float32)
    support = np.zeros((size, size), np.float32)
    instance_id = np.zeros((size, size), np.uint8)
    # Indexed by curve, not by draw order, so instances[k] always describes curves[k].
    instances = [np.zeros((size, size), np.uint8) for _ in curves]
    signal = np.zeros((size, size), np.float32)

    order = rng.permutation(len(curves))  # depth order: later fibers occlude earlier ones
    blur = float(rng.uniform(0.5, 1.5))
    for rank, ci in enumerate(order):
        curve = curves[ci]
        pts = np.rint(curve).astype(np.int32)
        width = float(rng.uniform(*width_range))
        sk = np.zeros((size, size), np.uint8)
        cv2.polylines(sk, [pts], False, 1, 1, cv2.LINE_8)
        instances[ci] = sk
        center |= sk
        instance_id[sk > 0] = ci + 1

        tube = np.zeros((size, size), np.uint8)
        cv2.polylines(tube, [pts], False, 1, max(1, int(round(width))), cv2.LINE_8)
        mask |= tube
        overlap += tube.astype(np.uint16)

        radiance = gaussian_filter(tube.astype(np.float32), blur)
        # Cotton fibers are convoluted ribbons: brightness beats along the fiber axis.
        beat = 0.72 + 0.28 * np.sin(xx / rng.uniform(6, 26) + yy / rng.uniform(6, 26)
                                    + rng.uniform(0, 6.3))
        gain = float(rng.uniform(0.16, 0.52)) * (0.75 + 0.25 * rank / max(len(order) - 1, 1))
        signal = np.maximum(signal, gain * radiance * beat)
        signal += rng.uniform(0.0, 0.04) * gaussian_filter(tube.astype(np.float32), 4.0)

        local = np.zeros((4, size, size), np.float32)
        hit = np.zeros((size, size), np.uint8)
        for j in range(len(pts) - 1):
            d = curve[j + 1] - curve[j]
            theta = float(np.arctan2(d[1], d[0]))
            a, b = tuple(pts[j]), tuple(pts[j + 1])
            cv2.line(hit, a, b, 1, 5)
            for k, val in enumerate((np.cos(2 * theta), np.sin(2 * theta),
                                     np.cos(4 * theta), np.sin(4 * theta))):
                cv2.line(local[k], a, b, float(val), 5)
        moments += local
        support += hit
    moments /= np.maximum(support, 1.0)[None]

    if fades and len(curves):
        keep = np.ones((size, size), np.float32)
        for _ in range(int(fades)):
            c = curves[int(rng.integers(len(curves)))]
            k = int(rng.integers(0, len(c)))
            span = int(rng.integers(4, 14))
            seg = np.rint(c[max(0, k - span):k + span]).astype(np.int32)
            m = np.zeros((size, size), np.uint8)
            cv2.polylines(m, [seg], False, 1, 9, cv2.LINE_8)
            m = gaussian_filter(m.astype(np.float32), 2.0)
            keep = np.minimum(keep, 1.0 - m * (1.0 - float(rng.uniform(0.05, 0.4))))
        signal = signal * keep
    for curve in distractors:
        pts = np.rint(curve).astype(np.int32)
        tube = np.zeros((size, size), np.uint8)
        cv2.polylines(tube, [pts], False, 1, max(1, int(round(rng.uniform(1.0, 4.0)))),
                      cv2.LINE_8)
        radiance = gaussian_filter(tube.astype(np.float32), blur)
        signal = np.maximum(signal, float(rng.uniform(0.10, 0.50)) * radiance)

    # Unlabelled distractors: dust motes and substrate speckle stay in the image and are
    # deliberately NOT in any label, so the network is trained to reject them.
    for _ in range(int(rng.integers(0, 26))):
        px, py = rng.integers(0, size, 2)
        bg = bg + rng.uniform(0.02, 0.14) * np.exp(
            -((xx - px) ** 2 + (yy - py) ** 2) / rng.uniform(1.0, 6.0))
    noise = rng.normal(0, rng.uniform(0.002, 0.016), (size, size))
    grain = gaussian_filter(rng.normal(0, rng.uniform(0.004, 0.014), (size, size)), 0.7)
    image = np.clip(bg + signal + noise + grain, 0, 1)
    if rng.random() < 0.45:
        image = gaussian_filter(image, rng.uniform(0.3, 0.9))
    return (image * 255).astype(np.uint8), dict(
        mask=mask, center=center, overlap=overlap, moments=moments,
        support=support, instance_id=instance_id, instances=instances)


def build_targets(parts, records, size):
    yy, xx = np.mgrid[:size, :size].astype(np.float32)
    heat = np.zeros((size, size), np.float32)
    for r in records:
        px, py = r["xy"]
        heat = np.maximum(heat, np.exp(-((xx - px) ** 2 + (yy - py) ** 2) / (2 * 3.2 ** 2)))
    center_soft = np.clip(gaussian_filter(parts["center"].astype(np.float32), 0.8) * 2.2, 0, 1)
    inst = parts["instances"]
    return dict(
        mask=parts["mask"],
        center=(center_soft * 255).astype(np.uint8),
        joint=(heat * 255).astype(np.uint8),
        moments=(np.clip(parts["moments"], -1, 1) * 127).astype(np.int8),
        orientation_valid=(parts["support"] > 0).astype(np.uint8),
        overlap=np.clip(parts["overlap"], 0, 3).astype(np.uint8),
        instance_id=parts["instance_id"],
        instances=(np.stack(inst) if inst else np.zeros((0, size, size), np.uint8)),
        points=np.array([r["xy"] for r in records], np.float32).reshape(-1, 2),
        points_complete=np.array([r["complete"] for r in records], np.uint8).reshape(-1),
    )


def interference_sample(rng, size, n_fibers):
    """Distractor curves and fade count for one canvas (interference-aware corpus).

    Lengths are absolute pixels, 16-200 px, far below any staple the plates can show,
    so none of them can be mistaken for a fiber by the label definition.
    """
    area = size * size / 100_000.0
    n = int(rng.integers(0, int(3 * area) + 2))
    curves = [worm_chain(rng, rng.uniform(0, 1, 2) * size, rng.uniform(0, 2 * np.pi),
                         float(rng.uniform(16.0, 200.0)), float(rng.uniform(15.0, 250.0)))
              for _ in range(n)]
    return curves, int(rng.integers(0, 2 * n_fibers + 1))


# --------------------------------------------------------------------------- driver
def carrier_library(real_root, size, limit=192):
    root = Path(real_root)
    rows = [r for r in load_json(root / "tiles.json") if r["split"] == "train"]
    if not rows:
        raise ValueError("no training-split tiles available as background carriers")
    rows.sort(key=lambda r: -r["signal_score"])
    pick = np.linspace(0, len(rows) - 1, min(limit, len(rows))).astype(int)
    out = []
    for i in pick:
        tile = suppress_fibers(read_image(root / rows[i]["path"], True))
        if tile.shape[0] < size or tile.shape[1] < size:
            tile = cv2.resize(tile, (max(size, tile.shape[1]), max(size, tile.shape[0])))
        out.append(tile)
    return out


def _carrier_crop(rng, library, size):
    tile = library[int(rng.integers(len(library)))]
    h, w = tile.shape
    y = int(rng.integers(0, max(h - size, 0) + 1))
    x = int(rng.integers(0, max(w - size, 0) + 1))
    crop = tile[y:y + size, x:x + size]
    crop = np.rot90(crop, int(rng.integers(4)))
    if rng.random() < 0.5:
        crop = np.fliplr(crop)
    return np.ascontiguousarray(crop).astype(np.float32)


def sample_carrier(rng, library, size):
    """A background carrier of arbitrary size, mosaicked from real suppressed tiles.

    Plate-sized canvases are larger than one tile, so overlapping crops are cross-faded;
    blending keeps the grain statistics of the real substrate without visible seams.
    """
    unit = min(library[0].shape[0], library[0].shape[1])
    if size <= unit:
        return _carrier_crop(rng, library, size).astype(np.uint8)
    acc = np.zeros((size, size), np.float32)
    weight = np.zeros((size, size), np.float32)
    taper = np.outer(np.hanning(unit), np.hanning(unit)).astype(np.float32) + 0.05
    step = unit // 2
    for y in range(0, size, step):
        for x in range(0, size, step):
            y0, x0 = min(y, size - unit), min(x, size - unit)
            acc[y0:y0 + unit, x0:x0 + unit] += _carrier_crop(rng, library, unit) * taper
            weight[y0:y0 + unit, x0:x0 + unit] += taper
    return np.clip(acc / np.maximum(weight, 1e-6), 0, 255).astype(np.uint8)


def generate(real="data/real", out="data/synth", size=384, plate_size=1024,
             counts=(4096, 256, 512), plate_count=64, staple=600.0, arm_pixels=56.0,
             margin_ratio=0.22, seed=1000, carrier_probability=0.75,
             equal_length=True, require_complete=True, interference=False):
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    library = carrier_library(real, max(size, plate_size // 2))
    margin = int(size * margin_ratio)
    rows = []
    specs = [("train", counts[0], size, 0), ("val", counts[1], size, 1_000_000),
             ("test", counts[2], size, 9_000_000), ("plate", plate_count, plate_size, 7_000_000)]
    specs = [s for s in specs if s[1] > 0]
    for split, n, canvas, offset in specs:
        (out / split).mkdir(exist_ok=True)
        cmargin = int(canvas * margin_ratio)
        for i in range(n):
            sample_seed = seed + offset + i
            rng = np.random.default_rng(sample_seed)
            case = str(rng.choice(CASES, p=CASE_P)) if split != "plate" else "multi"
            curves, records = make_geometry(rng, canvas, case, staple, arm_pixels, cmargin,
                                            equal_length=equal_length,
                                            require_complete=require_complete)
            carrier = (sample_carrier(rng, library, canvas)
                       if rng.random() < carrier_probability else None)
            distractors, fades = [], 0
            if interference:
                distractors, fades = interference_sample(rng, canvas, len(curves))
            image, parts = render(rng, curves, canvas, carrier, distractors=distractors,
                                  fades=fades)
            targets = build_targets(parts, records, canvas)
            stem = f"{split}/{i:05d}"
            write_image(out / f"{stem}.png", image)
            np.savez_compressed(out / f"{stem}.npz", **targets)
            save_json(out / f"{stem}.json", dict(
                seed=sample_seed, case=case, size=canvas, staple_pixels=staple,
                arm_pixels=arm_pixels, margin=cmargin,
                curves_xy=[c.tolist() for c in curves], crossings=records))
            rows.append(dict(id=stem, split=split, image=f"{stem}.png", target=f"{stem}.npz",
                             meta=f"{stem}.json", seed=sample_seed, case=case, size=canvas,
                             crossings=len(records),
                             complete_crossings=int(sum(r["complete"] for r in records)),
                             fibers=len(curves)))
            if (i + 1) % 200 == 0:
                print(f"synthetic {split} {i + 1}/{n}", flush=True)
    save_json(out / "manifest.json", rows)
    non_empty = [r for r in rows if r["case"] != "empty" and r["case"] != "near_miss"]
    save_json(out / "provenance.json", dict(
        generation_order="label first, image rendered from label",
        background_carrier_split="train only",
        staple_pixels=staple, nominal_staple_mm=35.0, arm_pixels=arm_pixels,
        canvas=size, plate_canvas=plate_size, counts=list(counts), plate_count=plate_count,
        seed=seed, carrier_probability=carrier_probability,
        equal_length=equal_length, require_complete=require_complete,
        interference=(dict(distractors="0-3 per 100k px2, 16-200 px of arc, unlabelled",
                           faded_stretches="0-2 per fiber, labels kept")
                      if interference else None),
        complete_crossing_guarantee=dict(
            rule="intersection interior by margin AND all four arms >= arm_pixels of arc "
                 "length inside the canvas",
            satisfied=int(sum(r["complete_crossings"] > 0 for r in non_empty)),
            of=len(non_empty)),
        label_semantics="projected 2D centerline geometry; depth order is rendered but "
                        "not exported as a physical contact claim"))
    preview(out, rows)
    print(f"synthetic complete: {len(rows)} canvases")
    return rows


def preview(out, rows, n=24, columns=6, thumb=192):
    picks = [r for r in rows if r["split"] == "train"][:n]
    cells = []
    for r in picks:
        img = read_image(Path(out) / r["image"], True)
        vis = cv2.cvtColor(cv2.resize(img, (thumb, thumb)), cv2.COLOR_GRAY2BGR)
        with np.load(Path(out) / r["target"]) as z:
            center = cv2.resize(z["center"], (thumb, thumb))
            pts = z["points"]
            comp = z["points_complete"]
            scale = thumb / r["size"]
        vis[center > 120] = (60, 230, 90)
        for p, c in zip(pts.reshape(-1, 2), comp.reshape(-1)):
            cv2.circle(vis, (int(p[0] * scale), int(p[1] * scale)), 7,
                       (40, 60, 255) if c else (0, 180, 255), 1, cv2.LINE_AA)
        cv2.putText(vis, r["case"], (4, 14), cv2.FONT_HERSHEY_SIMPLEX, 0.42, (255, 255, 255), 1)
        cells.append(vis)
    while len(cells) % columns:
        cells.append(np.zeros_like(cells[0]))
    grid = np.vstack([np.hstack(cells[i:i + columns]) for i in range(0, len(cells), columns)])
    write_image(Path(out) / "preview.jpg", grid)


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--real", default="data/real")
    p.add_argument("--out", default="data/synth")
    p.add_argument("--size", type=int, default=384)
    p.add_argument("--plate-size", type=int, default=1024)
    p.add_argument("--counts", type=int, nargs=3, default=[4096, 256, 512])
    p.add_argument("--plate-count", type=int, default=64)
    p.add_argument("--staple", type=float, default=600.0)
    p.add_argument("--arm-pixels", type=float, default=56.0)
    p.add_argument("--seed", type=int, default=1000)
    p.add_argument("--carrier-probability", type=float, default=0.75)
    p.add_argument("--no-equal-length", action="store_true")
    p.add_argument("--no-complete", action="store_true")
    a = p.parse_args()
    generate(a.real, a.out, a.size, a.plate_size, tuple(a.counts), a.plate_count,
             a.staple, a.arm_pixels, seed=a.seed,
             carrier_probability=a.carrier_probability,
             equal_length=not a.no_equal_length, require_complete=not a.no_complete)
