"""Optionally shrink the delivered project by dropping redundant checkpoints.

Every run writes four checkpoints.  Only `best.pt` is needed to reproduce a table row;
`last.pt` and `phase1.pt` exist for resuming training and for inspecting the state at the
end of the supervised phase.  This script removes the latter two from every run EXCEPT
the ones named by `--keep-full`, which stay complete.

Nothing is deleted unless you pass --apply, and the script prints what it would remove
first.  Removed checkpoints can be regenerated by re-running the training.

    python scripts/tools/slim_runs.py                 # report only
    python scripts/tools/slim_runs.py --apply
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

DROPPABLE = ("last.pt", "phase1.pt", "source_only.pt")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--runs", default="runs")
    p.add_argument("--keep-full", nargs="*", default=["cfxnet_s42"])
    p.add_argument("--apply", action="store_true")
    a = p.parse_args()

    keep = set(a.keep_full)
    total = 0
    victims = []
    for run in sorted((ROOT / a.runs).rglob("*")):
        if not run.is_dir() or not (run / "best.pt").exists():
            continue
        if run.name in keep:
            continue
        for name in DROPPABLE:
            path = run / name
            if path.exists():
                total += path.stat().st_size
                victims.append(path)
    for path in victims:
        print(f"  {'removing' if a.apply else 'would remove'} "
              f"{path.relative_to(ROOT).as_posix()}")
        if a.apply:
            path.unlink()
    print(f"{'freed' if a.apply else 'would free'} {total / 2**30:.2f} GiB "
          f"across {len(victims)} files; best.pt kept everywhere, "
          f"full checkpoints kept for {sorted(keep)}")
    if not a.apply:
        print("re-run with --apply to actually delete")


if __name__ == "__main__":
    main()
